name: Rust build, test, and generate specification

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      # Using our own runners for now:
      # - name: Free up disk space
      #   run: |
      #     sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cd24790a7f5f6439ac32cc94f5523cb2de8bfa8c # use-mise-action-v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise build
      - run: mise docker:start
    
      - name: Reference Test
        env:
          TEST_DB: REFERENCE
        continue-on-error: ${{ github.ref_name == 'main' }}
        run: |
          mise test

      - name: MongoDB Test
        env:
          TEST_DB: MONGODB
          MONGODB: mongodb://localhost
        continue-on-error: ${{ github.ref_name == 'main' }}
        run: |
          mise test

